export enum EstadoPedido {
    PENDIENTE = 'PENDIENTE',
    CONFIRMADO = 'CONFIRMADO',
    LISTO = 'LISTO',
    ENTREGADO = 'ENTREGANDO',
    CONFIRMADO_CLIENTE = 'CONFIRMADO_CLIENTE',
    PAGANDO = 'PAGANDO',
    TERMINADO = 'TERMINADO',
}